version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - givegetgo-network
    env_file:
      .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
  givegetgo-network:
    driver: bridge
