version: '3.8'
services:
  user-service:
    build:
      context: ./server/user_server
    ports:
      - "8081:8080"
    env_file:
      - ./server/user_server/.env.user
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - user-postgres
      - redis

  user-postgres:
    image: postgres
    container_name: user-postgres
    ports:
      - "5433:5432"
    networks:
      - givegetgo-network
    env_file:
      - ./server/user_server/.env.user
    volumes:
      - user-postgres:/var/lib/postgresql/data

  verification-service:
    build:
      context: ./server/verification_server
    ports:
      - "8082:8080"
    env_file:
      - ./server/verification_server/.env.verification
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - verification-postgres
      - redis

  verification-postgres:
    image: postgres
    container_name: verification-postgres
    ports:
      - "5434:5432"
    networks:
      - givegetgo-network
    env_file:
      - ./server/verification_server/.env.verification
    volumes:
      - verification-postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - givegetgo-network
    env_file:
      - ./server/shared/redis/.env.redis
    volumes:
      - redis:/data

volumes:
  user-postgres:
  verification-postgres:
  redis:

networks:
  givegetgo-network:
    driver: bridge
