version: '3.8'
services:
  server: 
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env.server
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - givegetgo-network
    env_file:
      .env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - givegetgo-network
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:

networks:
  givegetgo-network:
    driver: bridge
