name: GiveGetGo CI Workflow

on:
  pull_request:
    branches: [ main, development ]

jobs:
  servers:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: servers
    steps:
    - uses: actions/checkout@v4

    - name: Set up the latest stable Go version
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'
    
    - name: Install dependencies for user_server
      run: |
        cd user
        go get -v ./...

    - name: Install dependencies for verification_server
      run: |
        cd verification
        go get -v ./...

  # Uncomment and adapt the following if you have tests for each service
    # - name: Running tests for shared
    #   run: |
    #     cd shared
    #     go test -v ./...

    # - name: Running tests for user_server
    #   run: |
    #     cd user_server
    #     go test -v ./...

    # - name: Running tests for verification_server
    #   run: |
    #     cd verification_server
    #     go test -v ./...

    - name: Build the user_server service
      run: |
        cd user
        go build -v ./...

    - name: Build the verification_server service
      run: |
        cd verification
        go build -v ./...
