name: GiveGetGo CI Workflow

on:
  pull_request:
    branches: [ main, development ]

jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: 🔧 Install npm@latest
      run: npm i -g npm@latest

    - name: Install npm dependencies
      run: npm install

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Linting errors for our app...
      run: npm run lint

    # - name: Running tests for our app...
    #   run: npm test

    - name: Build Expo project...
      run: expo build

  client_web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client_web
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: 🔧 Install npm@latest
      run: npm i -g npm@latest

    - name: Install dependencies
      run: npm install
    
    # - name: Running tests for our website...
    #   run: npm test

    - name: Linting errors for our website...
      run: npm run lint

    - name: Trying to build the website...
      run: npm run build

  servers:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: servers
    steps:
    - uses: actions/checkout@v4

    - name: Set up the latest stable Go version
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'
    
    - name: Install dependencies for user_server
      run: |
        cd user
        go get -v ./...

    - name: Install dependencies for verification_server
      run: |
        cd verification
        go get -v ./...

  # Uncomment and adapt the following if you have tests for each service
    # - name: Running tests for shared
    #   run: |
    #     cd shared
    #     go test -v ./...

    # - name: Running tests for user_server
    #   run: |
    #     cd user_server
    #     go test -v ./...

    # - name: Running tests for verification_server
    #   run: |
    #     cd verification_server
    #     go test -v ./...

    - name: Build the user_server service
      run: |
        cd user
        go build -v ./...

    - name: Build the verification_server service
      run: |
        cd verification
        go build -v ./...
